security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    providers:
        our_db_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        main:
            pattern:    ^/
            http_basic: ~
            provider: our_db_provider
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: profile
                always_use_default_target_path: true
            logout:
                path:   /auth/logout
                target: /auth/login
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }